### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by mgibbs189** [BrilliantPlugins/geometa-facet#1]
Hey @stuporglue, FacetWP author here.

A customer just pointed me to this repo. Great work! I cannot believe I haven't seen this before...

Let me know if you need a dev license or anything. Also, if interested I'd be happy to promote it via our add-ons page: https://facetwp.com/add-ons/third-party/

**Comment by stuporglue** [comment]
Thanks @mgibbs189! 

I'll talk with my team and see if we're ready to be featured. We're big fans of FacetWP and customers have been very pleased with it too.

**Comment by nciske** [comment]
@mgibbs189 

I emailed you with our account details. 

Thanks for the generous offer!
